### ISSUE TITLE
Backward illegal memory access

### ISSUE THREAD

**Issue by fabvio** [mancinimassimiliano/pytorch_wbn#2]
Hi, I'm trying to use your layer, but I encountered a strange issue. I correctly included it in my network, it correctly calculates the weighted normalization in forward, but when I try to call a backward it gives the following error:

```THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1532579245307/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu line=266 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "train.py", line 455, in <module>
    t = Trainer(parser.parse_args())
  File "train.py", line 60, in __init__
    self.train()
  File "train.py", line 71, in train
    train_loss_d1, train_loss_d2 = self.trainOneEpoch(i)
  File "train.py", line 312, in trainOneEpoch
    loss_value.backward(retain_graph=True)
  File "/localhome/c-fpizzati/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/localhome/c-fpizzati/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1532579245307/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:266
```

Do you have any idea? I'm on torch 0.4.1 cuda 9.2.

**Comment by mancinimassimiliano** [comment]
Hi @fabvio, I tried to reproduce your issue, but I did not manage to (same pytorch, python and cuda versions). 
I have added to the repo the test I used (file `test_wbn.py`). Could you please try to run it, to check whether it depends directly on the WBN layers/compilation or on something else?

**Comment by mancinimassimiliano** [comment]
`test_wbn.py`

**Comment by fabvio** [comment]
Ok, it's working. I will investigate the error later and update the issue if I find something useful. Thanks a lot!

**Comment by wjx2** [comment]
I have get the same error, have you solved this problem? @fabvio @mancinimassimiliano

**Comment by wjx2** [comment]
I encountered the same problem, have you solved this problem? @mancinimassimiliano @fabvio

**Comment by mancinimassimiliano** [comment]
Hi @wjx2. have you tried running `test_wbn.py`? Does it run correctly?

**Comment by semi-supervised-paper** [comment]
I encountered the same problem, have you solved this problem? @mancinimassimiliano @fabvio
ps: running test.wbn.py in one forward gives correct results, but when I run the forward and backward function in several epochs,  an illegal memory access was encountered.

**Comment by mancinimassimiliano** [comment]
Hi @semi-supervised-paper ,
Did you encounter the error doing multiple forward and backward passes on `test_wbn.py` or using your training function? In case it is the latter, could you please provide me the code causing the problem so I can try to replicate the error? (I will do the same obviously if the error pops up after multiple iterations within  `test_wbn.py`). Thanks!

**Comment by semi-supervised-paper** [comment]
Hi @mancinimassimiliano ,
I test the code using wide resnet, and I've shown the code below.

````
import torch
import torch.nn as nn
import torch.nn.functional as F
import wbn_layers as wbn_layers
from functions import wbn as wbn_f


def conv3x3(i_c, o_c, stride=1):
    return nn.Conv2d(i_c, o_c, 3, stride, 1, bias=False)

class Identity(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__()
    
    def forward(self, x):
        return x

class BatchNorm2d(nn.Module):
    def __init__(self, channels, momentum=1e-3, eps=1e-3):
        super().__init__()
        self.abn = wbn_layers.WBN2d(num_features=channels, 
                                    eps=eps, 
                                    momentum=momentum,
                                    affine=True,
                                    k=2)
        print('-----------', self.abn.wbns[1].running_mean.size(), self.abn.wbns[1].running_var.size())

    def forward(self, x):
        w = F.softmax(torch.FloatTensor(x.size(0), 2).cuda(), dim=1)
        return self.abn.forward(x, w)

def relu():
    return nn.LeakyReLU(0.1)

class residual(nn.Module):
    def __init__(self, input_channels, output_channels, stride=1, activate_before_residual=False):
        super().__init__()
        layer = []
        if activate_before_residual:
            self.pre_act = nn.Sequential(
                BatchNorm2d(input_channels),
                relu()
            )
        else:
            self.pre_act = Identity()
            layer.append(BatchNorm2d(input_channels))
            layer.append(relu())
        layer.append(conv3x3(input_channels, output_channels, stride))
        layer.append(BatchNorm2d(output_channels))
        layer.append(relu())
        layer.append(conv3x3(output_channels, output_channels))

        if stride >= 2 or input_channels != output_channels:
            self.identity = nn.Conv2d(input_channels, output_channels, 1, stride, bias=False)
        else:
            self.identity = Identity()

        self.layer = nn.Sequential(*layer)

    def forward(self, x):
        x = self.pre_act(x)
        return self.identity(x) + self.layer(x)

class WRN(nn.Module):
    """ WRN28-width with leaky relu (negative slope is 0.1)"""
    def __init__(self, width, num_classes, transform_fn=None):
        super().__init__()

        self.init_conv = conv3x3(3, 16)

        filters = [16, 16*width, 32*width, 64*width]

        unit1 = [residual(filters[0], filters[1], activate_before_residual=True)] + \
            [residual(filters[1], filters[1]) for _ in range(1, 4)]
        self.unit1 = nn.Sequential(*unit1)

        unit2 = [residual(filters[1], filters[2], 2)] + \
            [residual(filters[2], filters[2]) for _ in range(1, 4)]
        self.unit2 = nn.Sequential(*unit2)

        unit3 = [residual(filters[2], filters[3], 2)] + \
            [residual(filters[3], filters[3]) for _ in range(1, 4)]
        self.unit3 = nn.Sequential(*unit3)

        self.unit4 = nn.Sequential(*[BatchNorm2d(filters[3]), relu(), nn.AdaptiveAvgPool2d(1)])

        self.output = nn.Linear(filters[3], num_classes)

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")    
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight)
                nn.init.constant_(m.bias, 0)

        self.transform_fn = transform_fn

    def forward(self, x):
        if self.training and self.transform_fn is not None:
            x = self.transform_fn(x)
        x = self.init_conv(x)
        x = self.unit1(x)
        x = self.unit2(x)
        x = self.unit3(x)
        f = self.unit4(x)
        c = self.output(f.squeeze())
        return c
                
                

model = WRN(2, 10).cuda()


for _ in range(10):
    x = torch.FloatTensor(10, 3, 32, 32).uniform_().to('cuda')
    output = model(x)

    y = torch.cuda.LongTensor([0, 0, 1, 1, 2, 3, 4, 5, 7, 1])

    loss = F.cross_entropy(output, y)
    loss.backward()
````
And the error is:
![image](https://user-images.githubusercontent.com/45139676/86094651-66027100-bae3-11ea-9553-2a0403d72b77.png)


The code is ok when replacing WBN with BN.

Thanks.

**Comment by mancinimassimiliano** [comment]
Thanks @semi-supervised-paper!

I think the problem is linked to the fact that the weights `w` do not require any gradient.  I tried the following variants (all requiring gradients for `w`) and they work:

1:
```
class BatchNorm2d(nn.Module):
def __init__(self, channels, momentum=1e-3, eps=1e-3):
        super().__init__()
        self.abn = wbn_layers.WBN2d(num_features=channels, 
                                    eps=eps, 
                                    momentum=momentum,
                                    affine=True,
                                    k=2)
    def forward(self, x):
        w0 = torch.FloatTensor(x.size(0), 2).cuda()
        w0.requires_grad=True
        w = F.softmax(w0, dim=1)
        return self.abn.forward(x, w)
```

2:
```
class BatchNorm2d(nn.Module):
    def __init__(self, channels, momentum=1e-3, eps=1e-3):
        super().__init__()
        self.abn = wbn_layers.WBN2d(num_features=channels, 
                                    eps=eps, 
                                    momentum=momentum,
                                    affine=True,
                                    k=2)

    def forward(self, x):
        w = F.softmax(torch.nn.Parameter(torch.FloatTensor(x.size(0), 2).uniform_().cuda()), dim=1)
        return self.abn.forward(x, w)
```

If you can try them out,  let me know if these solve your problem.

**Comment by semi-supervised-paper** [comment]
@mancinimassimiliano Thanks for your kindly response. The solution works for me !

**Comment by semi-supervised-paper** [comment]
@mancinimassimiliano  I found a bug when I try to use it in my code. When I forward the model multiple times and sum the loss each time, the backward part is blocked.

````
import torch
import torch.nn as nn
import torch.nn.functional as F
import wbn_layers as wbn_layers
from functions import wbn as wbn_f


def conv3x3(i_c, o_c, stride=1):
    return nn.Conv2d(i_c, o_c, 3, stride, 1, bias=False)

class Identity(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__()
    
    def forward(self, x):
        return x

class BatchNorm2d(nn.Module):
    def __init__(self, channels, momentum=1e-3, eps=1e-3):
        super().__init__()
        self.abn = wbn_layers.WBN2d(num_features=channels, 
                                    eps=eps, 
                                    momentum=momentum,
                                    affine=True,
                                    k=2)
        print('-----------', self.abn.wbns[1].running_mean.size(), self.abn.wbns[1].running_var.size())

    def forward(self, x):
        w0 = torch.FloatTensor(x.size(0), 2).cuda()
        w0.requires_grad=True
        w = F.softmax(w0, dim=1)
        return self.abn.forward(x, w)

def relu():
    return nn.LeakyReLU(0.1)

class residual(nn.Module):
    def __init__(self, input_channels, output_channels, stride=1, activate_before_residual=False):
        super().__init__()
        layer = []
        if activate_before_residual:
            self.pre_act = nn.Sequential(
                BatchNorm2d(input_channels),
                relu()
            )
        else:
            self.pre_act = Identity()
            layer.append(BatchNorm2d(input_channels))
            layer.append(relu())
        layer.append(conv3x3(input_channels, output_channels, stride))
        layer.append(BatchNorm2d(output_channels))
        layer.append(relu())
        layer.append(conv3x3(output_channels, output_channels))

        if stride >= 2 or input_channels != output_channels:
            self.identity = nn.Conv2d(input_channels, output_channels, 1, stride, bias=False)
        else:
            self.identity = Identity()

        self.layer = nn.Sequential(*layer)

    def forward(self, x):
        x = self.pre_act(x)
        return self.identity(x) + self.layer(x)

class WRN(nn.Module):
    """ WRN28-width with leaky relu (negative slope is 0.1)"""
    def __init__(self, width, num_classes, transform_fn=None):
        super().__init__()

        self.init_conv = conv3x3(3, 16)

        filters = [16, 16*width, 32*width, 64*width]

        unit1 = [residual(filters[0], filters[1], activate_before_residual=True)] + \
            [residual(filters[1], filters[1]) for _ in range(1, 4)]
        self.unit1 = nn.Sequential(*unit1)

        unit2 = [residual(filters[1], filters[2], 2)] + \
            [residual(filters[2], filters[2]) for _ in range(1, 4)]
        self.unit2 = nn.Sequential(*unit2)

        unit3 = [residual(filters[2], filters[3], 2)] + \
            [residual(filters[3], filters[3]) for _ in range(1, 4)]
        self.unit3 = nn.Sequential(*unit3)

        self.unit4 = nn.Sequential(*[BatchNorm2d(filters[3]), relu(), nn.AdaptiveAvgPool2d(1)])

        self.output = nn.Linear(filters[3], num_classes)

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")    
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight)
                nn.init.constant_(m.bias, 0)

        self.transform_fn = transform_fn

    def forward(self, x):
        if self.training and self.transform_fn is not None:
            x = self.transform_fn(x)
        x = self.init_conv(x)
        x = self.unit1(x)
        x = self.unit2(x)
        x = self.unit3(x)
        f = self.unit4(x)
        c = self.output(f.squeeze())
        return c
                
                

model = WRN(2, 10).cuda()


for _ in range(10):
    x = torch.FloatTensor(10, 3, 32, 32).uniform_().to('cuda')
    output = model(x)
    output2 = model(x)

    y = torch.cuda.LongTensor([0, 0, 1, 1, 2, 3, 4, 5, 7, 1])

    loss = F.cross_entropy(output, y)
    loss2 = F.cross_entropy(output2, y)
    all_loss = (loss+loss2)
    all_loss.backward()
    
````

See the code above. There are two losses in the code, and when the backward function was called, I got the following error:
 
![image](https://user-images.githubusercontent.com/45139676/86115891-234e9200-baff-11ea-80f9-242df586ac16.png)

Could you please figure out what happened?
Thanks

**Comment by mancinimassimiliano** [comment]
Thank you very much @semi-supervised-paper.

Glad to hear the first issue has gone (I actually traced it back and there is an issue when the tensor needed during the backward pass of the domain weights is not initialized). 

For the second, it was a tricky bug: it was not caused by multiple losses but multiple forward passes. Basically, the running statistics were overwritten and this was causing the problem. Since those where used just as a way to keep track of dimensions, I fixed this by making the function store the current mean and variances.
I modified only [functions.py](https://github.com/mancinimassimiliano/pytorch_wbn/tree/fix_multiforward/functions.py) and I pushed all the changes in a different branch: [fix_multiforward](https://github.com/mancinimassimiliano/pytorch_wbn/tree/fix_multiforward). Now it should work even if the weights do not need gradient (with a temporary fix, i.e. letting the function initialize the tensor).

Nothing is changed computationally wise thus I am 99% sure the new branch works fine. However, I will merge the changes only when I have time to redo the sanity checks on the gradients (I have to re-write them from scratch, unfortunately).

@semi-supervised-paper: if you have time, could you please check the new branch out and tell me if you encounter any problem?
@fabvio, @wjx2: I do not know if you managed to solve the problem. In case, could you please check the new branch out and tell me if it works for your cases as well?

**Comment by semi-supervised-paper** [comment]
@mancinimassimiliano  Thanks very much for your time to solve the problem, and the new codes can be run without exception. Amazing at how quickly you solve problems, and thanks again for your patience.

**Comment by mancinimassimiliano** [comment]
You are welcome! :) 
Actually, thank you all for the help in discovering and replicating the issues!
